version: '2'

services:
  script:
    build: ./src
    volumes:
      - ./src:/src
    network_mode: "host"

  redis:
    image: redis
    ports:
      - "6379"

  mynodeapp:
    build: ./node_app
    ports:
      - "3000:3000"
    links:
      - redis
